name: contract test

on: [push]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: unit_test
        run: |
          cd contract
          npm install
          npx hardhat test
